-- Script para popular o banco com 50 cursos e lições aleatórias
-- Cursos
INSERT INTO Course (id, name) VALUES (1, 'Curso 1');
INSERT INTO Course (id, name) VALUES (2, 'Curso 2');
INSERT INTO Course (id, name) VALUES (3, 'Curso 3');
INSERT INTO Course (id, name) VALUES (4, 'Curso 4');
INSERT INTO Course (id, name) VALUES (5, 'Curso 5');
INSERT INTO Course (id, name) VALUES (6, 'Curso 6');
INSERT INTO Course (id, name) VALUES (7, 'Curso 7');
INSERT INTO Course (id, name) VALUES (8, 'Curso 8');
INSERT INTO Course (id, name) VALUES (9, 'Curso 9');
INSERT INTO Course (id, name) VALUES (10, 'Curso 10');
INSERT INTO Course (id, name) VALUES (11, 'Curso 11');
INSERT INTO Course (id, name) VALUES (12, 'Curso 12');
INSERT INTO Course (id, name) VALUES (13, 'Curso 13');
INSERT INTO Course (id, name) VALUES (14, 'Curso 14');
INSERT INTO Course (id, name) VALUES (15, 'Curso 15');
INSERT INTO Course (id, name) VALUES (16, 'Curso 16');
INSERT INTO Course (id, name) VALUES (17, 'Curso 17');
INSERT INTO Course (id, name) VALUES (18, 'Curso 18');
INSERT INTO Course (id, name) VALUES (19, 'Curso 19');
INSERT INTO Course (id, name) VALUES (20, 'Curso 20');
INSERT INTO Course (id, name) VALUES (21, 'Curso 21');
INSERT INTO Course (id, name) VALUES (22, 'Curso 22');
INSERT INTO Course (id, name) VALUES (23, 'Curso 23');
INSERT INTO Course (id, name) VALUES (24, 'Curso 24');
INSERT INTO Course (id, name) VALUES (25, 'Curso 25');
INSERT INTO Course (id, name) VALUES (26, 'Curso 26');
INSERT INTO Course (id, name) VALUES (27, 'Curso 27');
INSERT INTO Course (id, name) VALUES (28, 'Curso 28');
INSERT INTO Course (id, name) VALUES (29, 'Curso 29');
INSERT INTO Course (id, name) VALUES (30, 'Curso 30');
INSERT INTO Course (id, name) VALUES (31, 'Curso 31');
INSERT INTO Course (id, name) VALUES (32, 'Curso 32');
INSERT INTO Course (id, name) VALUES (33, 'Curso 33');
INSERT INTO Course (id, name) VALUES (34, 'Curso 34');
INSERT INTO Course (id, name) VALUES (35, 'Curso 35');
INSERT INTO Course (id, name) VALUES (36, 'Curso 36');
INSERT INTO Course (id, name) VALUES (37, 'Curso 37');
INSERT INTO Course (id, name) VALUES (38, 'Curso 38');
INSERT INTO Course (id, name) VALUES (39, 'Curso 39');
INSERT INTO Course (id, name) VALUES (40, 'Curso 40');
INSERT INTO Course (id, name) VALUES (41, 'Curso 41');
INSERT INTO Course (id, name) VALUES (42, 'Curso 42');
INSERT INTO Course (id, name) VALUES (43, 'Curso 43');
INSERT INTO Course (id, name) VALUES (44, 'Curso 44');
INSERT INTO Course (id, name) VALUES (45, 'Curso 45');
INSERT INTO Course (id, name) VALUES (46, 'Curso 46');
INSERT INTO Course (id, name) VALUES (47, 'Curso 47');
INSERT INTO Course (id, name) VALUES (48, 'Curso 48');
INSERT INTO Course (id, name) VALUES (49, 'Curso 49');
INSERT INTO Course (id, name) VALUES (50, 'Curso 50');

INSERT INTO Lesson (id, name, course_id) VALUES (1, 'Lição 1', 1);
INSERT INTO Lesson (id, name, course_id) VALUES (2, 'Lição 2', 1);
INSERT INTO Lesson (id, name, course_id) VALUES (3, 'Lição 3', 1);
INSERT INTO Lesson (id, name, course_id) VALUES (4, 'Lição 4', 2);
INSERT INTO Lesson (id, name, course_id) VALUES (5, 'Lição 5', 2);
INSERT INTO Lesson (id, name, course_id) VALUES (6, 'Lição 6', 2);
INSERT INTO Lesson (id, name, course_id) VALUES (7, 'Lição 7', 3);
INSERT INTO Lesson (id, name, course_id) VALUES (8, 'Lição 8', 3);
INSERT INTO Lesson (id, name, course_id) VALUES (9, 'Lição 9', 3);
INSERT INTO Lesson (id, name, course_id) VALUES (10, 'Lição 10', 3);
INSERT INTO Lesson (id, name, course_id) VALUES (11, 'Lição 11', 4);
INSERT INTO Lesson (id, name, course_id) VALUES (12, 'Lição 12', 4);
INSERT INTO Lesson (id, name, course_id) VALUES (13, 'Lição 13', 5);
INSERT INTO Lesson (id, name, course_id) VALUES (14, 'Lição 14', 5);
INSERT INTO Lesson (id, name, course_id) VALUES (15, 'Lição 15', 5);
INSERT INTO Lesson (id, name, course_id) VALUES (16, 'Lição 16', 6);
INSERT INTO Lesson (id, name, course_id) VALUES (17, 'Lição 17', 6);
INSERT INTO Lesson (id, name, course_id) VALUES (18, 'Lição 18', 6);
INSERT INTO Lesson (id, name, course_id) VALUES (19, 'Lição 19', 7);
INSERT INTO Lesson (id, name, course_id) VALUES (20, 'Lição 20', 7);
INSERT INTO Lesson (id, name, course_id) VALUES (21, 'Lição 21', 8);
INSERT INTO Lesson (id, name, course_id) VALUES (22, 'Lição 22', 8);
INSERT INTO Lesson (id, name, course_id) VALUES (23, 'Lição 23', 8);
INSERT INTO Lesson (id, name, course_id) VALUES (24, 'Lição 24', 9);
INSERT INTO Lesson (id, name, course_id) VALUES (25, 'Lição 25', 9);
INSERT INTO Lesson (id, name, course_id) VALUES (26, 'Lição 26', 10);
INSERT INTO Lesson (id, name, course_id) VALUES (27, 'Lição 27', 10);
INSERT INTO Lesson (id, name, course_id) VALUES (28, 'Lição 28', 10);
INSERT INTO Lesson (id, name, course_id) VALUES (29, 'Lição 29', 11);
INSERT INTO Lesson (id, name, course_id) VALUES (30, 'Lição 30', 12);
INSERT INTO Lesson (id, name, course_id) VALUES (31, 'Lição 31', 13);
INSERT INTO Lesson (id, name, course_id) VALUES (32, 'Lição 32', 13);
INSERT INTO Lesson (id, name, course_id) VALUES (33, 'Lição 33', 14);
INSERT INTO Lesson (id, name, course_id) VALUES (34, 'Lição 34', 14);
INSERT INTO Lesson (id, name, course_id) VALUES (35, 'Lição 35', 15);
INSERT INTO Lesson (id, name, course_id) VALUES (36, 'Lição 36', 15);
INSERT INTO Lesson (id, name, course_id) VALUES (37, 'Lição 37', 15);
INSERT INTO Lesson (id, name, course_id) VALUES (38, 'Lição 38', 16);
INSERT INTO Lesson (id, name, course_id) VALUES (39, 'Lição 39', 16);
INSERT INTO Lesson (id, name, course_id) VALUES (40, 'Lição 40', 17);
INSERT INTO Lesson (id, name, course_id) VALUES (41, 'Lição 41', 17);
INSERT INTO Lesson (id, name, course_id) VALUES (42, 'Lição 42', 18);
INSERT INTO Lesson (id, name, course_id) VALUES (43, 'Lição 43', 18);
INSERT INTO Lesson (id, name, course_id) VALUES (44, 'Lição 44', 18);
INSERT INTO Lesson (id, name, course_id) VALUES (45, 'Lição 45', 19);
INSERT INTO Lesson (id, name, course_id) VALUES (46, 'Lição 46', 19);
INSERT INTO Lesson (id, name, course_id) VALUES (47, 'Lição 47', 20);
INSERT INTO Lesson (id, name, course_id) VALUES (48, 'Lição 48', 20);
INSERT INTO Lesson (id, name, course_id) VALUES (49, 'Lição 49', 21);
INSERT INTO Lesson (id, name, course_id) VALUES (50, 'Lição 50', 21);
INSERT INTO Lesson (id, name, course_id) VALUES (51, 'Lição 51', 22);
INSERT INTO Lesson (id, name, course_id) VALUES (52, 'Lição 52', 22);
INSERT INTO Lesson (id, name, course_id) VALUES (53, 'Lição 53', 23);
INSERT INTO Lesson (id, name, course_id) VALUES (54, 'Lição 54', 23);
INSERT INTO Lesson (id, name, course_id) VALUES (55, 'Lição 55', 24);
INSERT INTO Lesson (id, name, course_id) VALUES (56, 'Lição 56', 24);
INSERT INTO Lesson (id, name, course_id) VALUES (57, 'Lição 57', 25);
INSERT INTO Lesson (id, name, course_id) VALUES (58, 'Lição 58', 25);
INSERT INTO Lesson (id, name, course_id) VALUES (59, 'Lição 59', 26);
INSERT INTO Lesson (id, name, course_id) VALUES (60, 'Lição 60', 26);
INSERT INTO Lesson (id, name, course_id) VALUES (61, 'Lição 61', 27);
INSERT INTO Lesson (id, name, course_id) VALUES (62, 'Lição 62', 27);
INSERT INTO Lesson (id, name, course_id) VALUES (63, 'Lição 63', 28);
INSERT INTO Lesson (id, name, course_id) VALUES (64, 'Lição 64', 28);
INSERT INTO Lesson (id, name, course_id) VALUES (65, 'Lição 65', 29);
INSERT INTO Lesson (id, name, course_id) VALUES (66, 'Lição 66', 29);
INSERT INTO Lesson (id, name, course_id) VALUES (67, 'Lição 67', 30);
INSERT INTO Lesson (id, name, course_id) VALUES (68, 'Lição 68', 30);
INSERT INTO Lesson (id, name, course_id) VALUES (69, 'Lição 69', 31);
INSERT INTO Lesson (id, name, course_id) VALUES (70, 'Lição 70', 31);
INSERT INTO Lesson (id, name, course_id) VALUES (71, 'Lição 71', 32);
INSERT INTO Lesson (id, name, course_id) VALUES (72, 'Lição 72', 32);
INSERT INTO Lesson (id, name, course_id) VALUES (73, 'Lição 73', 33);
INSERT INTO Lesson (id, name, course_id) VALUES (74, 'Lição 74', 33);
INSERT INTO Lesson (id, name, course_id) VALUES (75, 'Lição 75', 34);
INSERT INTO Lesson (id, name, course_id) VALUES (76, 'Lição 76', 34);
INSERT INTO Lesson (id, name, course_id) VALUES (77, 'Lição 77', 35);
INSERT INTO Lesson (id, name, course_id) VALUES (78, 'Lição 78', 35);
INSERT INTO Lesson (id, name, course_id) VALUES (79, 'Lição 79', 36);
INSERT INTO Lesson (id, name, course_id) VALUES (80, 'Lição 80', 36);
INSERT INTO Lesson (id, name, course_id) VALUES (81, 'Lição 81', 37);
INSERT INTO Lesson (id, name, course_id) VALUES (82, 'Lição 82', 37);
INSERT INTO Lesson (id, name, course_id) VALUES (83, 'Lição 83', 38);
INSERT INTO Lesson (id, name, course_id) VALUES (84, 'Lição 84', 38);
INSERT INTO Lesson (id, name, course_id) VALUES (85, 'Lição 85', 39);
INSERT INTO Lesson (id, name, course_id) VALUES (86, 'Lição 86', 39);
INSERT INTO Lesson (id, name, course_id) VALUES (87, 'Lição 87', 40);
INSERT INTO Lesson (id, name, course_id) VALUES (88, 'Lição 88', 40);
INSERT INTO Lesson (id, name, course_id) VALUES (89, 'Lição 89', 41);
INSERT INTO Lesson (id, name, course_id) VALUES (90, 'Lição 90', 41);
INSERT INTO Lesson (id, name, course_id) VALUES (91, 'Lição 91', 42);
INSERT INTO Lesson (id, name, course_id) VALUES (92, 'Lição 92', 42);
INSERT INTO Lesson (id, name, course_id) VALUES (93, 'Lição 93', 43);
INSERT INTO Lesson (id, name, course_id) VALUES (94, 'Lição 94', 43);
INSERT INTO Lesson (id, name, course_id) VALUES (95, 'Lição 95', 44);
INSERT INTO Lesson (id, name, course_id) VALUES (96, 'Lição 96', 44);
INSERT INTO Lesson (id, name, course_id) VALUES (97, 'Lição 97', 45);
INSERT INTO Lesson (id, name, course_id) VALUES (98, 'Lição 98', 45);
INSERT INTO Lesson (id, name, course_id) VALUES (99, 'Lição 99', 46);
INSERT INTO Lesson (id, name, course_id) VALUES (100, 'Lição 100', 46);
INSERT INTO Lesson (id, name, course_id) VALUES (101, 'Lição 101', 47);
INSERT INTO Lesson (id, name, course_id) VALUES (102, 'Lição 102', 47);
INSERT INTO Lesson (id, name, course_id) VALUES (103, 'Lição 103', 48);
INSERT INTO Lesson (id, name, course_id) VALUES (104, 'Lição 104', 48);
INSERT INTO Lesson (id, name, course_id) VALUES (105, 'Lição 105', 49);
INSERT INTO Lesson (id, name, course_id) VALUES (106, 'Lição 106', 49);
INSERT INTO Lesson (id, name, course_id) VALUES (107, 'Lição 107', 50);
INSERT INTO Lesson (id, name, course_id) VALUES (108, 'Lição 108', 50);